apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: team-selector-demo
  title: Team Selector Template
  description: >
    Example template demonstrating a custom TeamSelector field
    that fetches dummy team data from an external API.
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Team Selection
      description: Choose a team fetched from an external dummy API.
      required: ['team']
      properties:
        team:
          type: string
          title: Select a Team
          ui:field: TeamSelector
          ui:options:
            apiUrl: 'https://dummyjson.com/users'
            
    - title: Select ClusterType and Env 
      description: Choose a cluster / approvedDesigns fetch from ServiceNow.
      required: ['cluster','approvedDesign']
      properties:
        cluster:
          type: string
          title: Select a ClusterType
          ui:field: ServiceNowExtension
          ui:options:
            apiUrl: 'https://dev308515.service-now.com/api/now/table/x_1856211_archit_0_approved_clusters?sysparm_limit=10'
        approvedDesign:
          type: string
          title: Select a Approved Architecture Designs
          ui:field: ServiceNowApprovedArchDesign
          ui:options:
            apiUrl: 'https://dev308515.service-now.com/api/now/table/x_1856211_demoapp_architecture_approved_designs?sysparm_limit=10'   

  steps:
    - id: log
      name: Log Selected Team
      action: debug:log
      input:
        message: >
          The selected team is: ${{ parameters.team }} ${{ parameters.cluster }} {{parameters.approvedDesign}}

  output:
    text:
      - title: Selected Team
        content: 'You selected: ${{ parameters.team }} ${{ parameters.cluster }} {{parameters.approvedDesign}}'
