apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
   name: aws-infra-template
   title: AWS EKS + RDS + S3 Terraform Template
   description: Creates a Terraform project with EKS, RDS Postgres, and S3 bucket.
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Application & Repository Info
      required:
        - repo_name
        - app_name
        - org_name
      properties:

        app_name:
          title: Application Name
          type: string
          description: Name of the application this infra is for

        repo_name:
          title: Repository Name
          type: string
          description: Name of the Git repository to create

        org_name:
          title: Organization Name
          type: string
          description: GitHub organization where the repo will be created
            
    - title: Select ClusterType and Approved Architect Designs 
      description: Choose a Cluster / Approved Design fetch from ServiceNow.
      required: ['cluster','approvedDesign']
      properties:
        cluster:
          type: string
          title: ClusterType
          description: This Data is fetched from Service Now via API
          ui:field: ServiceNowExtension
          ui:options:
            apiUrl: 'https://dev308515.service-now.com/api/now/table/x_1856211_archit_0_approved_clusters?sysparm_limit=10'
        approvedDesign:
          type: string
          title: Approved Architecture Designs
          description: This Data is fetched from Service Now via API
          ui:field: ServiceNowApprovedArchDesign
          ui:options:
            apiUrl: 'https://dev308515.service-now.com/api/now/table/x_1856211_demoapp_architecture_approved_designs?sysparm_limit=10'   

    - title: Infrastructure Settings
      required:
        - cluster_name
        - db_name
        - s3_bucket_name
        - db_username
        - db_password
      properties:
        cluster_name:
          title: EKS Cluster Name
          type: string
          description: Name of the AWS EKS cluster

        db_name:
          title: RDS Database Name
          type: string
          description: Name of the RDS PostgreSQL database

        s3_bucket_name:
          title: S3 Bucket Name
          type: string
          description: Name of the S3 bucket to be created

        db_username:
          title: RDS Username
          type: string
          description: Username for RDS instance

        db_password:
          title: RDS Password
          type: string
          ui:field: Secret
          description: Password for RDS instance        

  steps:
    - id: fetch
      name: Generating Terraform Artifacts
      action: fetch:template
      input:
        url: ./terraform-sample-template/skeleton
        targetPath: .
        values: ${{ parameters }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.org_name }}&repo=${{ parameters.repo_name }}
        description: Infrastructure for ${{ parameters.app_name }}
        defaultBranch: main
        protectDefaultBranch: true

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
    
    - id: log
      name: Log Selected Team
      action: debug:log
      input:
        message: >
          Cluster ${{ parameters.cluster }} ${{ parameters.approvedDesign }}

  output:
    text:
      - title: Selected Team
        content: 'You selected: ${{ parameters.cluster }} ${{parameters.approvedDesign}}'
