apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: Infrastructure resources for the ${{ values.app_name }} application
  annotations:
    github.com/project-slug: ${{ values.org_name }}/${{ values.repo_name }}
    terraform/organization: orgName
    terraform/workspaces: workspaceName1,workspaceName2,workspaceName
  links: 
    - url: "https://dev308515.service-now.com/now/nav/ui/classic/params/target/incident.do?sys_id=${{ values.sys_id}}"
      title: ${{ values.incident_number }}
      icon: web  
  tags:
    - EKS
    - ApprovedDesign
    - Terraform
    - Provisioning
spec:
  type: service
  lifecycle: production
  owner: user/arunhari82
